train:
  mode: "vae"
  debug: false
  remove_exp_dir: true
  trajdata_cache_location: "~/my_custom_cache_location"

  training:
    batch_size: 1
    num_steps: 50000
    num_data_workers: 1

  validation:
    enabled: true
    batch_size: 32
    num_data_workers: 18
    every_n_steps: 1000
    num_steps_per_epoch: 50  

  trajdata_source_train:
    # - "nusc_trainval-train"
    # - "nusc_trainval-train_val"
    - "nusc_mini-mini_train"
  trajdata_source_valid:
    # - "nusc_trainval-val" 
    - "nusc_mini-mini_val"
  trajdata_data_dirs:
    nusc_trainval: "/home/visier/nuscenes"
    nusc_test: "/home/visier/nuscenes"
    nusc_mini: "/home/visier/nuscenes"

  trajdata_rebuild_cache: false # 原来是false
  parallel_strategy: "ddp"
  rollout:
    enabled: false
    save_video: false
    every_n_steps: 5000
    warm_start_n_steps: 0

  save:
    enabled: true
    every_n_steps: 4000
    best_k: 3
    save_best_rollout: false
    save_best_validation: true

  on_ngc: false

  logging:
    terminal_output_to_txt: true
    log_tb: false
    log_wandb: false
    wandb_project_name: "hf_visier"
    log_every_n_steps: 200
    flush_every_n_steps: 500
  
  datamodule_class: "PassUnifiedDataModule"
  training_vec_map_params: 
    S_seg: 15
    S_point: 80
    map_max_dist: 80
    max_heading_error: 7853981633974483
    ahead_threshold: -40
    dist_weight: 1.0
    heading_weight: 0.1
env:
  name: "trajdata"
  data_generation_params:
    trajdata_centric: "agent"
    trajdata_only_types:
      - "vehicle"
    trajdata_predict_types:
      - "vehicle"
    trajdata_scene_desc_contains: null
    trajdata_incl_map: true
    trajdata_max_agents_distance: !!float inf
    trajdata_standardize_data: true
    other_agents_num: null

  rasterizer:
    include_hist: true
    num_sem_layers: 3
    drivable_layers: null
    rgb_idx_groups:
      - [0]
      - [1]
      - [2]
    raster_size: 224
    pixel_size: 0.5
    ego_center:
      - -0.5
      - 0.0
    no_map_fill_value: -1.0
algo:
  name: "dm_vae"
  eval_class: "dm_vae"
  coordinate: "agent_centric"
  scene_agent_max_neighbor_dist: 30
  map_encoder_model_arch: "resnet18"
  diffuser_model_arch: "TemporalMapUnet"
  disable_control_on_stationary: "current_speed"
  moving_speed_th: 0.5
  rasterized_history: true
  rasterized_map: true
  use_map_feat_global: true
  use_map_feat_grid: false
  base_dim: 32
  horizon: 52
  n_diffusion_steps: 100
  action_weight: 1
  diffusor_loss_weights: null
  loss_discount: 1
  predict_epsilon: false
  dim_mults:
    - 2
    - 4
    - 8
  clip_denoised: false
  loss_type: "l2"
  use_ema: true
  ema_step: 1
  ema_decay: 0.995
  ema_start_step: 4000
  diffuser_building_block: "concat"
  action_loss_only: false
  diffuser_input_mode: "state_and_action"
  use_reconstructed_state: false
  conditioning_drop_map_p: 0.0
  conditioning_drop_neighbor_p: 0.0
  conditioning_drop_fill: 0.5
  cond_feat_dim: 256
  curr_state_feat_dim: 64
  map_feature_dim: 256
  map_grid_feature_dim: 32
  history_feature_dim: 128
  history_num_frames: 30
  history_num_frames_ego: 30
  history_num_frames_agents: 30
  future_num_frames: 52
  step_time: 0.1
  render_ego_history: false
  decoder: 
    layer_dims: []
    state_as_input: true
        
  dynamics:
    type: "Unicycle"
    max_steer: 0.5
    max_yawvel: 6.283185307179586
    acce_bound:
      - -10
      - 8
    ddh_bound:
      - -6.283185307179586
      - 6.283185307179586
    max_speed: 40.0
  loss_weights:
    diffusion_loss: 1.0

  optim_params:
    dm:
      learning_rate:
        initial: 0.0002
        decay_factor: 0.1
        epoch_schedule:
          - 15
          - 30
      regularization:
        L2: 0.0
    vae:
      learning_rate:
        initial: 0.0002
        decay_factor: 0.5
        epoch_schedule:
          - 10
          - 20
      regularization:
        L2: 0.01

  nusc_norm_info:
    diffuser:
      - [2.135494, 0.003704, 0.970226, 0.000573, -0.002965, 0.000309]
      - [5.5444, 0.524067, 2.206522, 0.049049, 0.729327, 0.023765]
    agent_hist:
      - [-1.198923, 0.000128, 0.953161, 4.698113, 2.051664]
      - [3.180241, 0.159182, 2.129779, 2.116855, 0.388149]
    neighbor_hist:
      - [-0.237441, 1.118636, 0.489575, 0.868664, 0.222984]
      - [7.587311, 7.444489, 1.680952, 2.578202, 0.832563]
  trajectory_shape: [52,6]
  latent_dim: 128
root_dir: "/home/visier/hazardforge/visier_logs"
name: "test"
seed: 1
