train:
  mode: "ppo"
  debug: false

  trajdata_cache_location: "~/my_custom_cache_location"
  plt_interval: 1000
  plt_indices: [0,10,20,30]
  
  checkpoint_vae: '/home/visier/hazardforge/HazardForge/logs/2025-02-16 11:28:47/checkpoints/iterstep=1258_epepoch=1---val/loss.ckpt'
  checkpoint_dm: '/home/visier/hazardforge/HazardForge/logs/2025-02-17 17:25:25 dm/checkpoints/iterstep=2370_epepoch=14---val/loss.ckpt'
  checkpoint_rl: null

  training:
    batch_size: 64
    epochs: 50
    num_steps: 600
    num_data_workers: 20

  validation:
    batch_size: 64
    every_n_steps: 500
    num_steps_per_epoch: 1 #每次validation时,运行多少step
    num_data_workers: 20
    enabled: true
  save:
    every_n_steps: 3000
    best_k: 1
    enabled: true

  logging:
    terminal_output_to_txt: true
    wandb_project_name: "Visier_VAE"
    log_every_n_steps: 50             #the frequency of wandb refresh
    flush_every_n_steps: 500
  trajdata_source_train:
    - "nusc_trainval-train"
    - "nusc_trainval-train_val"
    # - "nusc_mini-mini_train"
  trajdata_source_valid:
    - "nusc_trainval-val" 
    # - "nusc_mini-mini_val"

  wandb_dir: "logs"
  

  trajdata_data_dirs:
    nusc_trainval: "/home/visier/nuscenes"
    nusc_test: "/home/visier/nuscenes"
    nusc_mini: "/home/visier/nuscenes"

  trajdata_rebuild_cache: false
  parallel_strategy: "ddp"
  rollout:
    enabled: false
    save_video: false
    every_n_steps: 5000
    warm_start_n_steps: 0

  

  on_ngc: false

 
  

  training_vec_map_params: 
    S_seg: 15
    S_point: 80
    map_max_dist: 80
    max_heading_error: 7853981633974483
    ahead_threshold: -40
    dist_weight: 1.0
    heading_weight: 0.1
env:
  name: "trajdata"
  data_generation_params:
    trajdata_centric: "agent"
    trajdata_only_types:
      - "vehicle"
    trajdata_predict_types:
      - "vehicle"
    trajdata_scene_desc_contains: null
    trajdata_incl_map: true
    trajdata_max_agents_distance: 20
    trajdata_standardize_data: true            #设置为true则采用局部坐标系,以agent为原点| false 使用全局坐标系,真实轨迹数据
    other_agents_num: 10

  rasterizer:
    include_hist: true
    num_sem_layers: 3
    drivable_layers: null
    rgb_idx_groups:
      - [0]
      - [1]
      - [2]
    raster_size: 224
    pixel_size: 0.5
    ego_center:
      - -0.5
      - 0.0
    no_map_fill_value: -1.0

  simulation:
    num_simulation_steps: null
    start_frame_index: null
algo:
  name: "dm_vae"
  eval_class: "dm_vae"
  update_old_model_every: 20
  coordinate: "agent_centric"
  scene_agent_max_neighbor_dist: 30
  map_encoder_model_arch: "resnet18"
  diffuser_model_arch: "TemporalMapUnet"
  disable_control_on_stationary: ["any_speed","on_lane"]
  transition_in_dim: 6
  moving_speed_th: 0.5
  rasterized_history: true
  rasterized_map: true
  use_map_feat_global: true
  use_map_feat_grid: false
  base_dim: 32
  horizon: 52
  n_diffusion_steps: 100
  action_weight: 1
  diffusor_loss_weights: null
  loss_discount: 1
  predict_epsilon: false
  dim_mults:
    - 2
    - 4
    - 8
  clip_denoised: false
  loss_type: "l2"
  
  diffuser_building_block: "concat"

  cond_feat_dim: 256
  curr_state_feat_dim: 64
  map_feature_dim: 256
  map_grid_feature_dim: 32
  history_feature_dim: 128
  history_num_frames: 30
  history_num_frames_ego: 30
  history_num_frames_agents: 30
  future_num_frames: 52
  step_time: 0.1
  render_ego_history: false
  time_dim: 128
  num_infer: 3
  vae:
    hidden_size: 64
    latent_size: 4
  dynamics:
    type: "Unicycle"
    max_steer: 0.5
    max_yawvel: 6.283185307179586
    acce_bound:
      - -10
      - 8
    ddh_bound:
      - -6.283185307179586
      - 6.283185307179586
    max_speed: 40.0
  loss_weights:
    diffusion_loss: 1.0

  optim_params:
    dm:
      learning_rate:
        initial: 0.00005
      regularization:
        L2: 0
    vae:
      learning_rate:
        initial: 0.0001
        decay_factor: 0.5
        epoch_schedule:
          - 10
          - 20
      regularization:
        L2:  0.00001

  nusc_norm_info:
    diffuser:   
      - [13.162, -0.13891, 5.0223, -0.0046415, -0.0080072, -0.0013546] # standard=true
      - [13.0717, 2.2462, 3.6187, 0.2210, 2.5770, 0.0840]
  hist_encoder_hidden: 128

  num_samp: 4  # N
  ppo_num: 1    # M

  buffer_max: 30
  ppo_update_times: 50
  update_interval: 10

seed: 1
