name: hf
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - pip:
      - setuptools
      - torch
      - pyyaml
      - pytorch-lightning
      - pyemd
      - h5py
      - imageio-ffmpeg
      - python-louvain
      - nuscenes-devkit
      - protobuf



